### ISSUE TITLE
Add multi-component volume rendering support

### ISSUE THREAD

**Issue by thewtex** [Kitware/itk-vtk-viewer#122]
With multiple volume component, add a dropdown to support modification of the associated transfer function. Next to each component, and enable / disable checkbox could be present.

First address:

https://github.com/Kitware/vtk-js/issues/936

**Comment by GenevieveBuckley** [comment]
Do you have any advice for someone looking to take a crack at this?

**Comment by thewtex** [comment]
@GenevieveBuckley thanks for the interest.

Pointers are outlined in https://github.com/Kitware/vtk-js/issues/936 but @martinken is looking at addressing this.

**Comment by GenevieveBuckley** [comment]
No worries, thanks for the update

**Comment by martinken** [comment]
This has been merged to master.
