### ISSUE TITLE
The resulting production version is incorrect

### ISSUE THREAD

**Issue by lujx123** [Kitware/itk-vtk-viewer#138]
I tried to use NPM to generate a production version, but in the process of using, I reported an error, the error is as follows:
Uncaught (promise) in DOMException: Failed to construct a 'Worker' : Script at 'file:///H:/xm/itk-vtk-viewer/dist/itk/WebWorkers/ImageIO.worker.js' always be accessed from origin' null '.

**Comment by thewtex** [comment]
What exact steps should be taken to reproduce the error? i.e. commands?

**Comment by lujx123** [comment]
> What exact steps should be taken to reproduce the error? i.e. commands?

That's right.Operate by command

**Comment by thewtex** [comment]
What are the commands?
