### ISSUE TITLE
how to add a self-define lookuptable into the select?

### ISSUE THREAD

**Issue by yangdieyan** [Kitware/itk-vtk-viewer#139]

**Comment by thewtex** [comment]
One option is to refactor the target code into a module (PR welcome :-) ), then use a [WebPack alias](https://webpack.js.org/configuration/resolve/) to override the default.

**Comment by thewtex** [comment]
The code has now been refactored to use a colormap icon, and a custom colormap icon can be used (this functionality is used by [itkwidgets](https://github.com/InsightSoftwareConsortium/itkwidgets).
