### ISSUE TITLE
Is it possible to add a ruler tool, for interactively measuring features?

### ISSUE THREAD

**Issue by dsmyth** [Kitware/itk-vtk-viewer#174]
Similar to the gimp 'measure' tool. https://docs.gimp.org/2.10/en/gimp-tool-measure.html

**Comment by thewtex** [comment]
Yes, this should be possible.

@floryst what do you recommend as the best / latest / greatest widget to do this in vtk.js?

**Comment by floryst** [comment]
Hi! We currently do have angle and distance widgets in vtk.js. However, the currently checked-in code is not very UI-friendly to 2D views. I have worked on a nicer set of widgets, which I will merge into vtk.js soon. You can check the current state of them out in ParaView Glance [nightly](https://kitware.github.io/paraview-glance/nightly/) under the "tools" tab.

**Comment by dsmyth** [comment]
I have put a simple implementation submitted as [pull request 225](https://github.com/Kitware/itk-vtk-viewer/pull/225l)
