### ISSUE TITLE
Change interactorStyle3D during runtime

### ISSUE THREAD

**Issue by tunglt1810** [Kitware/itk-vtk-viewer#197]
Hi guys, 
The interactorStyle3D is fixed when init the viewport. How can i change the interactor style during runtime?

**Comment by thewtex** [comment]
@agirault @jourdain

**Comment by jourdain** [comment]
Can you explain what you are trying to do? Nothing should limit you from providing your own. Are you just missing access to the view instance? If you have access to the proxymanager, you can get your hand on the view.

**Comment by tunglt1810** [comment]
The default behavior of left mouse click event is rotate, and sometime i want to assign pan and zoom behavior to the left mouse

**Comment by jourdain** [comment]
Just call this [method](https://github.com/Kitware/vtk-js/blob/master/Sources/Proxy/Core/ViewProxy/index.js#L87)

**Comment by tunglt1810** [comment]
Thank you so much!
