### ISSUE TITLE
How to change Window Leveling interator? 

### ISSUE THREAD

**Issue by tunglt1810** [Kitware/itk-vtk-viewer#198]
Hi guys,
The window leveling behavior of vtk.js is fixed with Alt + Left mouse
[https://kitware.github.io/vtk-js/api/Interaction_Style_InteractorStyleImage.html](https://kitware.github.io/vtk-js/api/Interaction_Style_InteractorStyleImage.html)

I have try but still failed. How can i change this behavior?
![itk-vtk-window-tool-code](https://user-images.githubusercontent.com/19906349/70318237-2b3ca100-1852-11ea-8063-7ab998e26ad0.png)

**Comment by thewtex** [comment]
This is currently set up here:

https://github.com/Kitware/itk-vtk-viewer/blob/52f9c3cfa630a337da4064252131abf379860c00/src/UserInterface/Image/createTransferFunctionWidget.js#L233-L287

but refactoring may be required to make it configurable.

**Comment by tunglt1810** [comment]
Thanks, it's work for me
