### ISSUE TITLE
Mouse over event make viewport blur

### ISSUE THREAD

**Issue by tunglt1810** [Kitware/itk-vtk-viewer#199]
Hi guys,
When i hover over the viewport, the 3 image id blur and unsmooth. Is it a error of interactor?

**Comment by thewtex** [comment]
This is likely expected behavior related to level-of-detail rendering. Is there a video recording of the behavior?

**Comment by tunglt1810** [comment]
This is a screen record
![Peek 2019-12-13 08-57](https://user-images.githubusercontent.com/19906349/70763455-b6ec8b00-1d86-11ea-95e7-901a3f6d4ce4.gif)

**Comment by thewtex** [comment]
@tunglt1810 thanks, that is helpful.

There is stochastic jitter that is part of the volume rendering process. @martinken any ideas on how to make the jitter values fixed while the volume is "not moving"?

**Comment by jourdain** [comment]
Normally, moving the mouse should not trigger an animation and therefore no more rendering.

**Comment by thewtex** [comment]
@jourdain good idea! An animation was added to update the cursor widget (a cube) on the slice planes. This PR disables that when just looking at the volume rendering: https://github.com/Kitware/itk-vtk-viewer/pull/205. @tunglt1810 this fixes the behavior you reported.
