### ISSUE TITLE
Use absolute path for the webworker file

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#200]
As discussed with @thewtex during the hackathon, we try to use the UMD file hosted on UNPKG (https://unpkg.io/itk-vtk-viewer@9.6.0/dist/itkVtkViewer.js), we can start the viewer. 

However, when I try to load a local png file, it fails because it tries to load the webworker file from a relative path (/itk/WebWorkers/ImageIO.worker.js).

**Comment by oeway** [comment]
Update: I manually replaced the `itkModulesPath` in `itkVtkViewer.js` to an absolute url and it now works in ImJoy: https://imjoy.io/lite?plugin=oeway/ImJoy-Plugins:itk-vtk-viewer

Would be nice if you can update it or expose the config somewhere.

**Comment by thewtex** [comment]
@oeway thanks for filing the issue and publishing on ImJoy-Plugins -- love it! :heart: 

#202 exports `createViewer` and fixes the web-worker paths in `dist/itkVtkViewerCDN.js` to point to Unpkg.io.
