### ISSUE TITLE
Rendering method and algorithm

### ISSUE THREAD

**Issue by tunglt1810** [Kitware/itk-vtk-viewer#204]
Hi guys,
I'm a newbie of this domain. Today i read an [artical](https://home.hiroshima-u.ac.jp/~kin/publications/VolVis96/VolumeRendering.ps) about fast volumn rendering. Can you fast explain the rendering method/algorithm of vtk.js and color map function algorithm?
Thank you

**Comment by thewtex** [comment]
Hi @tunglt1810 vtk.js volume rendering is roughly based on the VTK volume rendering. More information can be found here:

- https://lorensen.github.io/VTKExamples/site/VTKBook/
- https://dl.acm.org/citation.cfm?id=3349091
