### ISSUE TITLE
Custom color map

### ISSUE THREAD

**Issue by tunglt1810** [Kitware/itk-vtk-viewer#210]
Hi guys,
The vtk.js has many preset [color map](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/ColorTransferFunction/ColorMaps.json). How can i add more custom color map?

**Comment by jourdain** [comment]
You can call that [method](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/ColorTransferFunction/ColorMaps.js#L25)
