### ISSUE TITLE
Fullscreen of black

### ISSUE THREAD

**Issue by tunglt1810** [Kitware/itk-vtk-viewer#229]
Hi guys,
Can you check this study. The viewer is fullscreen of black

https://drive.google.com/file/d/1U6GOvdXAXCVA2dvAe_hrnPjb1ZVwCDUp/view?usp=sharing

**Comment by thewtex** [comment]
Hi @tunglt1810 ,

This is fixed in 9.21.0. Here is the rendered data:

![image](https://user-images.githubusercontent.com/25432/79176237-ab10e400-7dcd-11ea-9e52-1c400cef56db.png)
