### ISSUE TITLE
Corner viewer: text hard to read with default lookup table

### ISSUE THREAD

**Issue by muellerflorian** [Kitware/itk-vtk-viewer#240]
First, thanks for this fantastic work!

I'm working with Wei Ouyang on ImJoy, and he uses the itk-vtk-viewer in a visualization plugin. 

When using the default look-up table (Viridis), it can be hard to read the corner viewer, since the font color collides with the lookup table (see screenshot below). 

It might be a nice feature to add an API function allowing the developer to change the text properties of the corner viewer (font, size, color). 

![Annotation 2020-03-24 095220](https://user-images.githubusercontent.com/10832779/77406781-7654d280-6db5-11ea-9381-97ad7d6e89ea.png)

**Comment by thewtex** [comment]
@muellerflorian thanks for the kind words and report!

@oeway added a CSS class in #241 -- does this serve your need?

**Comment by muellerflorian** [comment]
perfect. thanks a lot!
