### ISSUE TITLE
Failed to read DICOM images

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#245]
I am trying the viewer with [a DICOM image](http://medistim.com/wp-content/uploads/2016/07/bmode.dcm) from the PWA, however, it failed to read the image.

**Comment by thewtex** [comment]
It seems to have issues with that particular image. I am currently improving DICOM support -- we can try that image again soon.

**Comment by thewtex** [comment]
The issue here is likely the TransferSyntax:

> 1.2.840.10008.1.2.4.70 [JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression]

but I am surprised that we are observing errors.

**Comment by thewtex** [comment]
This was addressed in #259 via itk.js 12.2.0 :tada:
