### ISSUE TITLE
After loading data, render state is not yet consistent

### ISSUE THREAD

**Issue by scottwittenburg** [Kitware/itk-vtk-viewer#256]
The video below shows loading the `yeast_mito-T9-filtered.nrrd` data set.  Notice how selecting the tab for the color/opacity map at component index 1 results in a change to the image.  Simply opening the editor for these properties, but not changing any of them, should not cause the rendering to change.

![localhost_8080 (1)](https://user-images.githubusercontent.com/6527504/78684607-e7b07d00-78ad-11ea-9fe9-eeebe8832aa8.gif)

**Comment by thewtex** [comment]
The Gaussian in the transfer function widget is likely only applied to the first component that is selected -- we will have to cycle through all the components and apply the initial Gaussian as the piecewise function for each component in the rendering initialization logic.

**Comment by scottwittenburg** [comment]
Thanks @thewtex ⛑ I did try to do something like that, but I must not have found the right point in the rendering setup, as it didn't fix the problem.  I added some code to loop through all the components and do what you suggested at the bottom of the `createTransferFunctionWidget.js` module, but that seems not to be the right place.  I'll keep after it.
