### ISSUE TITLE
Wrong color map for common RGB images

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#257]
It seems the latest viewer cannot show regular JPEG/png images properly anymore, the default color map looks wired.

**Comment by scottwittenburg** [comment]
Hmmm, we're always setting `independentComponents = true` on the vtkImageMapper with the recent changes.  I wonder if showing JPEG/png images requires it to be `false`, thus invoking the previous shaders.

**Comment by thewtex** [comment]
Yes, if the data is 2D / Uint8Array / 3 or 4 component, we should assume `independentComponents = false`

**Comment by oeway** [comment]
It seems this issue comes back after recent PRs, now if we load a jpeg image for example, the color map is not correct by default. @thewtex

**Comment by thewtex** [comment]
@oeway is there a sample image file I should try? The PNG's and JPEG's I tried look good to me.

**Comment by oeway** [comment]
Hey, i tried a few on my mobile and some of them works indeed, but photos took from a camera doesn't work. Will try to provide some example image later.

I also noticed that in ImageJ.JS, https://ij.imjoy.io if I open a sample image via File-> samples -> flybrain, then  open it in Itk-vtk-viewer (in the plugin menu), the 3D image I got is reddish, while the previous version shows the correct RGB color in 3D.

**Comment by thewtex** [comment]
> Hey, i tried a few on my mobile and some of them works indeed, but photos took from a camera doesn't work. Will try to provide some example image later.

Great, thanks.

> I also noticed that in ImageJ.JS, https://ij.imjoy.io if I open a sample image via File-> samples -> flybrain, then open it in Itk-vtk-viewer (in the plugin menu), the 3D image I got is reddish, while the previous version shows the correct RGB color in 3D.

This sounds familiar during recent refactoring, but it may have been resolved -- is it still the case with current `master`?

**Comment by oeway** [comment]
@thewtex Here is one example with the RGB color image: https://images.proteinatlas.org/61448/1319_C10_2_blue_red_green.jpg  If I load it into the viewer, it [becomes reddish](https://kitware.github.io/itk-vtk-viewer/app/?fileToLoad=https://images.proteinatlas.org/61448/1319_C10_2_blue_red_green.jpg).

For 3D images, I confirm that the color issue has been fixed in ImageJ.JS. However, there seems some additional noise on the rendered images compared to the previous version: 
<img width="1332" alt="Screenshot 2021-02-01 at 22 24 39" src="https://user-images.githubusercontent.com/478667/106519972-611ff880-64dc-11eb-9aa4-056cb4d06980.png">
The noise is fixed when you zoom in and out, any idea?

**Comment by thewtex** [comment]
@oeway thanks for the detailed description and sample data.

We added the ability to dynamically generate multi-scale pyramids for non-zarr datasets so we can render large datasets based on the rendering capabilities of the client. Your JPEG data set is larger, so that is why we were only seeing it there. And that is why it was not an issue on the highest scale of the 3D volume.

Addressed in #364 

![localhost_8080__fileToLoad=https___images proteinatlas org_61448_1319_C10_2_blue_red_green jpg](https://user-images.githubusercontent.com/25432/106667534-0a1b3180-6577-11eb-8eeb-2574e4ee6a55.gif)

**Comment by oeway** [comment]
This is awesome! Thanks!
