### ISSUE TITLE
Embedded viewer no more loading

### ISSUE THREAD

**Issue by kerautret** [Kitware/itk-vtk-viewer#266]
Congratulation for your excellent viewer that is very nice to display online results and demonstration. Thanks a lot for your valuable work!

I detected something wrong by using the viewer like described here: https://kitware.github.io/itk-vtk-viewer/docs/embeddedViewer.html
It was perfectly working using old version less or equal to 9.18.0 (not tested all versions) like here:
http://ipol-geometry.loria.fr/SourceCodeDemosWorkshop/dist/testEmbeded9.18.0.html
But on using the current version (or same with 9.19.0) the viewer is not loading my test image (.nii)
http://ipol-geometry.loria.fr/SourceCodeDemosWorkshop/dist/testEmbededCurrent.html
http://ipol-geometry.loria.fr/SourceCodeDemosWorkshop/dist/testEmbeded9.19.0.html
I always get the same view : 
<img width="1119" alt="Capture d’écran 2020-04-23 à 14 48 08" src="https://user-images.githubusercontent.com/772865/80101267-780ae500-8571-11ea-8f33-cf68321e2617.png">

It looks like that the viewer is trying to read the first letter of the field:   data-url
<img width="1231" alt="Capture d’écran 2020-04-23 à 14 45 58" src="https://user-images.githubusercontent.com/772865/80101060-27938780-8571-11ea-9d5a-5e24a933a780.png">

By the way did there exist a way do display two image volume in one viewer ? (or mixing with a .obj file) ?

**Comment by scottwittenburg** [comment]
@kerautret Thanks for reporting this.  We recently added support for passing both an intensity image as well as a labelmap via the `fileToLoad` url parameter, and I suspect this may have broken the file loading for the embedded use case.  I'll look into it, and hopefully have a fix out quickly.

**Comment by scottwittenburg** [comment]
@kerautret I don't have a quick/easy way to test embedding the viewer, but I think the fix I just submitted should take of the problem.

**Comment by kerautret** [comment]
@scottwittenburg many thanks for your reply. I test it ;)

**Comment by kerautret** [comment]
Excellent the fix is perfectly working nice 🎉

**Comment by kerautret** [comment]
by the way did there exists a way to load several files ? or an mesh file?

**Comment by kerautret** [comment]
@scottwittenburg and by the way the load of several objects is also working, I see that différents objects can be added with , .
