### ISSUE TITLE
Default colors of mesh in embedded viewer. 

### ISSUE THREAD

**Issue by kerautret** [Kitware/itk-vtk-viewer#269]
I was wondering if it was possible to add an option to change the default mesh color that is displayed in embedded viewer. By default the user has to change the color of the reference mesh(initially in white in the example) in order to compare a result of an output algorithm. It could be very nice to make it automatically instead manually like in this example:  
![ezgif-7-a262a7a32e9e](https://user-images.githubusercontent.com/772865/80153916-bf6b9280-85be-11ea-9267-b48b2b496c32.gif)
Ideally something like "data-default-mesh-color="ff000040" in the <div> code could be perfect.
Perhaps an alternative could be to that I change it manually in the viewer code ?

**Comment by thewtex** [comment]
Hi @kerautret, how about changing the default mesh color to red? This is a better default in general since it contrasts with the image viridis colormap.

**Comment by kerautret** [comment]
@thewtex thanks a lot, yes it it to able to compare ground truth given in an mesh (obj file). I was trying to set a material in the obj file or using color in .off it could be perhaps more standard to change on the mesh. But it is nice I try it. And concerning the alpha value perhaps it is less standard to change (the idea is to show the quality answer of the algorithm by highlighting the false positive that will be visible outside the red color but the true positive will be hidden if we don't use alpha < 1.0

**Comment by kerautret** [comment]
I try the patch by the way ;)

**Comment by thewtex** [comment]
Since there are many visualization options, we are working towards the point where you can easily serialize / deserializer the viewer state, #165 with a JSON file.

> I try the patch by the way ;)

Thanks!

**Comment by kerautret** [comment]
you are welcome, nice idea the serialize/deserialize, I frequently use in other viewer the saving/pasing camera settings (like in QGLViewer viewer). But I wonder if such strategy will work in the embedded viewer mode ?

**Comment by thewtex** [comment]
Yes, we should be able to serialize / deserialize the state, including the camera state by using the [`getState()` function](https://kitware.github.io/vtk-js/docs/structures.html) on the [ItkVtkViewProxy](https://github.com/Kitware/itk-vtk-viewer/blob/3a56474e4c1bf3140fef5b590a91514a10791de2/src/ItkVtkViewProxy.js) class and the [serialization capabilities of mobx](https://github.com/mobxjs/serializr) on the [ViewerStore](https://github.com/Kitware/itk-vtk-viewer/blob/master/src/ViewerStore.js).
