### ISSUE TITLE
File loading functionality broken

### ISSUE THREAD

**Issue by scottwittenburg** [Kitware/itk-vtk-viewer#277]
It seems maybe after #275 was merged, we lost the ability to drag and drop files into the viewer.  Also, the `fileToLoad` url parameter doesn't seem to work anymore.  When I try to use these features, I don't see any errors in the console, but the viewer is black and the "image" parts of the ui are not generated.

<img width="681" alt="Screen Shot 2020-05-04 at 1 45 37 PM" src="https://user-images.githubusercontent.com/6527504/81006961-9abcb980-8e0d-11ea-80b6-446c4954fba0.png">

**Comment by scottwittenburg** [comment]
I guess using `filesToLoad` isn't the way to pass a label map and image via the url anymore, as the ability to tell them apart in that situation isn't very sophisticated, and now we should use `image` and `labelMap` url parameters.  However, it's still the case that simply dropping a single image file doesn't work anymore, and produces the result above.

**Comment by kerautret** [comment]
@scottwittenburg It is also the case in an embedded view like in the doc:
https://kitware.github.io/itk-vtk-viewer/docs/viewer.html
we obtain the same display...
![Capture d’écran 2020-05-05 à 10 19 37](https://user-images.githubusercontent.com/772865/81047055-ef1d7300-8eb9-11ea-82eb-06aef70889cb.png)

**Comment by thewtex** [comment]
@scottwittenburg @kerautret good catch -- yes `filesToLoad` should still be working as before.

This is addressed in #279 .
