### ISSUE TITLE
3d Rendering bug on Safari

### ISSUE THREAD

**Issue by kerautret** [Kitware/itk-vtk-viewer#281]
I was surprise to see a algorithm like the following image: 
![Capture d’écran 2020-05-06 à 21 37 51](https://user-images.githubusercontent.com/772865/81220670-00619f00-8fe2-11ea-8e1d-bd04c45342d2.png)
but by displaying the same link on Chrome I get the better awaited display:
<img width="773" alt="Capture d’écran 2020-05-06 à 21 37 56" src="https://user-images.githubusercontent.com/772865/81220777-28e99900-8fe2-11ea-924c-d9e5978d16d9.png">
(it also works on Firefox).
It looks related to the 3d rendering since the 2D plane are well displayed:
![Capture d’écran 2020-05-06 à 21 54 11](https://user-images.githubusercontent.com/772865/81222167-2720d500-8fe4-11ea-889f-95c127d70aa0.png)
I get no error message in the console, just a warning when I try to change the volume distance sampling parameter: (not sure that helps but nothing else).
![Capture d’écran 2020-05-06 à 21 53 30](https://user-images.githubusercontent.com/772865/81222331-6818e980-8fe4-11ea-87c0-0bc40548b789.png)

I can give you the sample if you want.

**Comment by thewtex** [comment]
Yes, I would be interested to see the dataset.

Is this a large dataset? Does increasing the volume distance sampling parameter help?

**Comment by kerautret** [comment]
It result from a Frangi filter from the sample of the itk-vtk-viewer. 26 Mo
You can get it here: https://filesender.renater.fr/?s=download&token=0af5bbab-e689-401e-9a2a-8473d1984a1b

**Comment by kerautret** [comment]
@thewtex I also get the strangely bug on other types of images like [here](https://ipol-geometry.loria.fr/~kerautre/ipol_demo/LiverVesselnessIPOLDemo/result?key=4E5BA981A063A671D4A8F226819B6D83)
If you want the image source:  [here](https://filesender.renater.fr/?s=download&token=5333dfe8-1ac3-42ea-8997-5bbe5cb5f1d5) (link available only until 05/06/2020)

**Comment by thewtex** [comment]
@kerautret this is how it is rendering for me on Linux / Chrome:

![image](https://user-images.githubusercontent.com/25432/82620890-a2b78000-9ba7-11ea-86a8-3a401dcd584b.png)

Is this what you are observing?

**Comment by thewtex** [comment]
And Firefox:

![image](https://user-images.githubusercontent.com/25432/82620947-c11d7b80-9ba7-11ea-870c-e78372cdcaee.png)

**Comment by kerautret** [comment]
No, your display are the correct one, and the one that I obtain is that:

![Capture d’écran 2020-05-22 à 13 42 15](https://user-images.githubusercontent.com/772865/82664548-36359300-9c32-11ea-83a7-62107a65a206.png)

If you have suggestion to something to change in the source code to test it let me know.

**Comment by thewtex** [comment]
@jourdain @martinken are these known issues on Safari?

**Comment by jourdain** [comment]
Safari is WebGL 1

**Comment by jourdain** [comment]
I think there is an option to make it run in Alpha/Beta with WebGL2

**Comment by kerautret** [comment]
@jourdain I try to activate webgl2 in the dev menu but the result is no more better I get an empty white view:
![Capture d’écran 2020-05-22 à 16 42 31](https://user-images.githubusercontent.com/772865/82679429-3f7f2980-9c4b-11ea-96ec-f6786e37ea8f.png)
![Capture d’écran 2020-05-22 à 16 42 06](https://user-images.githubusercontent.com/772865/82679441-427a1a00-9c4b-11ea-95b9-7122ad2c22a5.png)

**Comment by kerautret** [comment]
It looks fine with beta 1 of IOS 14!: (probably the case for MacOS Big Sur not yet testes)
![IMG_2803](https://user-images.githubusercontent.com/772865/85922747-fcd1f200-b885-11ea-86da-8553fcb215db.PNG)

**Comment by jourdain** [comment]
Great, thanks for sharing this information.

**Comment by thewtex** [comment]
For older Safari, this may address the issue: https://github.com/Kitware/vtk-js/pull/1539

We'll be updating vtk.js soon.

**Comment by kerautret** [comment]
Great! 👍🏻 I will try it when it will be updated, let me know if you want a try.

**Comment by kerautret** [comment]
thanks !

**Comment by thewtex** [comment]
@kerautret released in 10.7.0 -- testing and feedback would be appreciated!

**Comment by kerautret** [comment]
@thewtex I look it thanks!

**Comment by kerautret** [comment]
The problem looks to be always present: 😂
![Capture d’écran 2020-07-28 à 00 12 17](https://user-images.githubusercontent.com/772865/88597280-3190bf00-d067-11ea-80a1-0c5ffb139c25.png)

**Comment by kerautret** [comment]
(I compiled from the current master, and by the way I see that contrast curve are more available, is it expected ? (any way to show it again ?) It was very nice to display volume.

**Comment by martinken** [comment]
It is fixed for me tested with the foot dataset you provided. Are you sure you are using the right version?

**Comment by martinken** [comment]
Ahh different dataset. I would still expect my changes to fix this from a quick look

**Comment by thewtex** [comment]
@kerautret the contrast curve should be available, but I expect we are not seeing it because error occur before it renders.

Checking your build:

https://ipol-geometry.loria.fr/~kerautre/ipol_demo/LiverVesselnessIPOLDemo/result?key=4E5BA981A063A671D4A8F226819B6D83

Errors occur in the console like:

> Error: n[o].getText is not a function itkVtkViewerCDN.js:23:415558

This indicates a missing patch that I added to vtk.js before @martinken 's WebGL1 volume fix, so it appears the required vtk.js was not available in the build.

This does not occur in the [reference build](https://kitware.github.io/itk-vtk-viewer/). Note that a page refresh may be required to get the latest build.

So, please try running `npm ci` to clear the *node_modules* folder and re-install all dependencies.

**Comment by kerautret** [comment]
Thanks sorry you are right I just apply an `npm run-script build`

**Comment by kerautret** [comment]
🎉 nice all is good, Bravo! 
![Capture d’écran 2020-07-30 à 14 37 21](https://user-images.githubusercontent.com/772865/88923681-6329a600-d272-11ea-8816-bc814ab89c78.png)
