### ISSUE TITLE
Unsubscribing events causes console errors on next event

### ISSUE THREAD

**Issue by scottwittenburg** [Kitware/itk-vtk-viewer#288]
I created a simple test in my local environment to allow me to subscribe to the UI collapsed event. 
 While the event is subscribed, the behavior is as expected and I see the collapsed state printed out in the console.  However, once I call `subscription.unsubscribe()`, then all subsequent open/close of the UI result in a stack trace.  Here's the diff that allowed me to test the subscribe/unsubscribe functionality:

```
$ git diff
diff --git a/dist/index.html b/dist/index.html
index 9f3b1b1..7562905 100644
--- a/dist/index.html
+++ b/dist/index.html
@@ -47,6 +47,18 @@
       if (!viewer) {
         itkVtkViewer.createViewerFromLocalFiles(container);
       }
+      viewer.then((viewerObj) => {
+        var called = 0;
+        function handledUICollapsed(collapsed) {
+          called += 1
+          console.log('User interface is now ', collapsed);
+          if (called >= 4) {
+            console.log('unsubscribing')
+            subscription.unsubscribe()
+          }
+        }
+        var subscription = viewerObj.subscribeToggleUserInterfaceCollapsed(handledUICollapsed);
+      });
     </script>
   </body>
 </html>
```

The reason for the stack traces is that unsubscribing just sets the handler array location to null (here)[https://github.com/Kitware/itk-vtk-viewer/blob/master/src/createViewer.js#L461], and doesn't shift the remaining items to the left.  Additionally, the handler isn't checked for null before attempting to call it (here)[https://github.com/Kitware/itk-vtk-viewer/blob/master/src/createViewer.js#L453].

**Comment by scottwittenburg** [comment]
@thewtex I discovered this while working on the new event infrastructure, in trying to make sure I didn't break the existing functionality.

I wonder if the unsubscribe is mostly unused by folks embedding the application?

**Comment by thewtex** [comment]
> I wonder if the unsubscribe is mostly unused by folks embedding the application?

Yes, I think so ... the new infrastructure is likely a good improvement :-).
