### ISSUE TITLE
Resolution drops when the browser tab is inactive

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#296]
I just noticed that if you switch on auto rotation and leave the browser tab, the resolution of the volume drops gradually and becomes noisy.

The left is my normal volume, the right is the one when the resolutions goes bad
<img width="1528" alt="Screenshot 2020-06-03 at 15 28 18" src="https://user-images.githubusercontent.com/478667/83642257-e13d3980-a5ae-11ea-9a22-083b48ea47c8.png">

I can reproduce this bug by:
1. show a volume
2. switch on rotation
3. switch to another browser tab, and come back for multiple times, and you will see the resolution become worse and worse.

I am using the latest Chrome on MacOS 10.14.6.

**Comment by kerautret** [comment]
I also see it but I didn't consider it  as a bug because I was thinking that it was done in order to reduce ressource allocation when the view was not used.

**Comment by thewtex** [comment]
@martinken @scottwittenburg any ideas on ways recognize when we switch back to a tab and respond appropriately?

**Comment by martinken** [comment]
When a rendering goes into the background the browser probably pauses the animationFrame, when you go back it resumes it but that creates a really long time between frames which tells VTK it needs to reduce resolution. 

I suppose you could watch for a visibility changed event, and set some ivar that tells the interactor to ignore the next frame time, basically just skip it and keep using the prior time. That would maybe solve it for a bunch of common cases.

**Comment by thewtex** [comment]
Awesome, thanks for the tip, @martinken ! Addressed here: https://github.com/Kitware/vtk-js/pull/1500
