### ISSUE TITLE
2D Label map rendering

### ISSUE THREAD

**Issue by thewtex** [Kitware/itk-vtk-viewer#297]
Initialization does not appear to be working correctly for 2D label maps, e.g. the attached.
[cthead_labels.nrrd.zip](https://github.com/Kitware/itk-vtk-viewer/files/4748065/cthead_labels.nrrd.zip)

![cthead_labels](https://user-images.githubusercontent.com/25432/84070934-ea594c80-a99a-11ea-8d08-12244672fa91.png)

In the console, we get:

> [.WebGL-0x278c5511a800]GL ERROR :GL_INVALID_OPERATION : glTexImage2D: invalid internalformat/format/type combination GL_R8_EXT/GL_RG_EXT/GL_UNSIGNED_BYTE

**Comment by scottwittenburg** [comment]
Thanks for sharing the data to reproduce, I'll take a look.
