### ISSUE TITLE
No error reported when check WebGL failed

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#302]
Hi, just noticed createViewer returns null without error. Digging into it and found webGL crashed for some reason, restarting the browser fixes it but it's confusing to get a null return. I think a better behaviour is to throw an error with the actual error message. 

https://github.com/Kitware/itk-vtk-viewer/blob/4611de2206e3c97ebdfdf885d6872be63386f509/src/createViewer.js#L43-L45

**Comment by thewtex** [comment]
@oeway makes sense. Please take a look at https://github.com/Kitware/itk-vtk-viewer/pull/305
