### ISSUE TITLE
Clamp out of range colors to peak value

### ISSUE THREAD

**Issue by thewtex** [Kitware/itk-vtk-viewer#310]
When values exceed the min / max mapped color, they are present as black in the slices:

![image](https://user-images.githubusercontent.com/25432/85036353-0b1b6200-b152-11ea-9077-092c82a47b51.png)

Can they be clamped to the min / max value of the colormap? @scottwittenburg could you please help with this?

**Comment by scottwittenburg** [comment]
@thewtex Yes I'll take a look, thanks.

**Comment by scottwittenburg** [comment]
Just to make sure I'm trying to fix the right issue: I'm reproducing this by sliding that blue window level bar to, e.g., reduce the max mapped color value.  Like in this video?

![valueClampingIssue](https://user-images.githubusercontent.com/6527504/85094752-c7097b00-b1ac-11ea-848f-f59f18f0d938.gif)

**Comment by thewtex** [comment]
@scottwittenburg yes, where the cyan is turning black, we want to keep it cyan.

**Comment by jourdain** [comment]
Wondering if this is related to https://github.com/Kitware/vtk-js/issues/1499

**Comment by scottwittenburg** [comment]
Yep, I wondered too since the symptom looks identical, but it seems we're not using `discretize` from here, and it seems that's not the default.  I'm still looking into it though.  Thanks @jourdain.

**Comment by thewtex** [comment]
`git bisect` points to

54b7bf89b6c7b3b536dad9bd65c2d89dbb8bcc93

```
 +++ b/package.json
@@ -26,7 +26,7 @@
     "open": "^6.4.0",
     "promise-file-reader": "^1.0.2",
     "regenerator-runtime": "^0.13.5",
-    "vtk.js": "^14.1.2"
+    "vtk.js": "^14.3.2"
   },
   "devDependencies": {
     "@babel/plugin-transform-runtime": "^7.9.6",
```
