### ISSUE TITLE
npm run start doesn't open internet window

### ISSUE THREAD

**Issue by laurennlam** [Kitware/itk-vtk-viewer#338]
Hi,
I tried to launch the app localy by using comand line `npm run start`.
It seems that something is running but any adress is defined (like localhost:2020).
So I didn't know how to view the app.
Did I miss some documentation anywhere ? I tried localhost:3000 (as defined in cli.md) but without success.

So, I updated the package.json file : `"start": "webpack-dev-server --mode development --content-base ./dist/ --watch-content-base --host 0.0.0.0 --port 3000"` With this modification, it launches the app on 0.0.0.0 and use port 3000.

What's the best way to do that ?

**Comment by oeway** [comment]
I saw the same and did the same trick. 
I think we can make a PR to specify the port explicitly.

**Comment by thewtex** [comment]
Hi,

The default webpack-dev-server port is *8080*.

We could remove a development step and make this more obvious by opening a browser tab -- please try #339
