### ISSUE TITLE
multiscaleImage is not defined

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#368]
Noticed a bug here: https://github.com/Kitware/itk-vtk-viewer/blob/5c5dbfb12c2e0d7f2ab88631ea29b652425fe9de/src/imJoyPluginAPI.js#L28-L35
`multiscaleImage` is not defined, maybe we should remove the entire code block when there is no image passed in.

**Comment by thewtex** [comment]
Makes sense -- removed in https://github.com/Kitware/itk-vtk-viewer/pull/372

**Comment by oeway** [comment]
Thank you!
