### ISSUE TITLE
Unknown or unsupported pixel type when passing an ndarray

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#369]
When passing an ndarray constructed from a RGB image, the viewer failed to load the image and complaining `Unknown or unsupported pixel type: itk::CommonEnums::IOPixel::UNKNOWNPIXELTYPE`.

Try it here:
https://imjoy.io/lite?plugin=https://gist.github.com/oeway/5a8f4ce24111a26c39e0644a56bfe897

**Comment by thewtex** [comment]
@oeway what is the value of `imageType.pixelType` resulting from the `ndarray` conversion?

**Comment by oeway** [comment]
In the conversion function we have:
https://github.com/Kitware/itk-vtk-viewer/blob/94807c6385f1a4aec5d1e26d210292b56df13a62/src/IO/ndarrayToItkImage.js#L48-L49

This means if I pass an RGB image with 3 channels, the `pixelType` is `PixelTypes.VariableLengthVector`. Right now if I follow your suggestion in https://github.com/Kitware/itk-vtk-viewer/issues/367 to set the pixel type to `PixelTypes.VariableLengthVector` I got the same error.

**Comment by oeway** [comment]
This was fixed by https://github.com/Kitware/itk-vtk-viewer/pull/374
