### ISSUE TITLE
Image UI collapsed after hiding and showing the main UI

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#375]
See below:
![GUTJ4ba2Bd](https://user-images.githubusercontent.com/478667/108119351-f0faa080-709f-11eb-8296-ce72f76eda9f.gif)

The same issue is found in https://github.com/imjoy-team/kaibu/pull/50

**Comment by thewtex** [comment]
@oeway thanks for the nice GIF :framed_picture: 

#377 restores the select image layer interface when the UI in un-collapsed and adds an API function, `selectLayer`, to programmatically select the layer in Kaibu if needed.
