### ISSUE TITLE
Rendering bug for RGB images with only one channel

### ISSUE THREAD

**Issue by oeway** [Kitware/itk-vtk-viewer#380]
I found that if some of the channels are set to all 0, the viewer can easily go wrong:
For example this image: [_af647Cy5](https://user-images.githubusercontent.com/478667/108582412-76e24a00-7333-11eb-8dfb-6a97f7ed09c4.png)

If you download it and load it with the viewer https://kitware.github.io/itk-vtk-viewer/app/ it becomes all green, and complains an error: `itkVtkViewer.js:2 attempt to set zero width color range`.

Another observation is that, if we keep R channel, but set G and B to all 0, then it seems worked. If we keep only B or G, then the viewer does not work as expected.

@thewtex

**Comment by thewtex** [comment]
@oeway thanks for the report :+1: 

Addressed in #381 

![image](https://user-images.githubusercontent.com/25432/108790570-0ada2e80-754b-11eb-9ce9-7c87989b0450.png)
