### ISSUE TITLE
[Help] fileToLoad is not loading local files

### ISSUE THREAD

**Issue by rodrigomologni** [Kitware/itk-vtk-viewer#441]
Hi Team!

I would like to visualize local files using `?fileToLoad=` as shown in the image below, available at [Progressive Web App](https://kitware.github.io/itk-vtk-viewer/docs/viewer.html).

![image](https://user-images.githubusercontent.com/1608652/154775669-27025797-f54b-4e62-9d5f-fbcf48e060fe.png)

But it's not working. What am I doing wrong? If anyone could answer me, I'd appreciate it.

### Script

1. Create `C:\data`
2. Download https://data.kitware.com/api/v1/file/564a65d58d777f7522dbfb61/download/data.nrrd
3. Move `025_13months_T2_RegT1_Reg2Atlas_ManualBrainMask_Stripped.nrrd` to `C:\data`
4. Run `itk-vtk-viewer` from `C:\`

```
itk-vtk-viewer
  => Serving C:\ on port 3000

     vEthernet (Default Switch) => http://172.27.128.1:3000/
     vEthernet (Wi-Fi) => http://172.23.224.1:3000/
     Wi-Fi => http://192.168.1.103:3000/
     vEthernet (Ethernet) => http://172.30.16.1:3000/
```

5. Open `http://localhost:3000/?fileToLoad=/data/025_13months_T2_RegT1_Reg2Atlas_ManualBrainMask_Stripped.nrrd`

![image](https://user-images.githubusercontent.com/1608652/154774791-370bed87-6887-4334-b816-41b880937ddd.png)

**Comment by thewtex** [comment]
For security reasons, the browser intentionally does not provide access to the local filesystem.

**Comment by thewtex** [comment]
Note that the CLI is provided to load local filesystem files -- they can be passed as arguments.

**Comment by thewtex** [comment]
@rodrigomologni thanks for the follow-up! Addressed in #453

**Comment by rodrigomologni** [comment]
Hi @thewtex! Both are working now! Thank you very much! 🎉

I have a question, why `/data/` is added in the URL? For example:
```sh
itk-vtk-viewer BRUGGE60K_FY-SF-KM-1-1.vtp ==> http://172.22.144.1:3000/?fileToLoad=/data/BRUGGE60K_FY-SF-KM-1-1.vtp
```

**Comment by thewtex** [comment]
The `/data/` is just informational.

**Comment by rodrigomologni** [comment]
OK. Thanks!
