### ISSUE TITLE
Is there any way to assign coloring and disable rotation from the beginning on the embedded version?

### ISSUE THREAD

**Issue by Davegb** [Kitware/itk-vtk-viewer#463]
I'm creating a website that has an ITK viewer, but it rotates from the start and is in B/W. I'd like to change that. Is it possible?

**Comment by PaulHax** [comment]
Does this do it for you:
```
itkVtkViewer.createViewer(mount, {
      image: new URL('https://data.kitware.com/api/v1/file/564a65d58d777f7522dbfb61/download/data.nrrd'),
      rotate: false,
    }).then((viewer) => {
      viewer.setBackgroundColor([1, 1, 1])
      setTimeout(() => viewer.setImageColorMap('2hot', 0), 0)
    })
```

**Comment by Davegb** [comment]
Yup, that does the job! Just for the future, I'd like to mention a few things:

* `mount` refers to the div where the ITK viewer would be, so instead of mount, it would be `document.getElementsByClassName("itk-vtk-viewer")[0]`, or `document.getElementByID("viewer")` in case you assigned an ID to that div.
* The only attribute that you should put in the div tag is `data-viewport`. **It's important not to put** `data-url`, and the others are ignored.
* The accepted color map values are [here](https://github.com/Kitware/itk-vtk-viewer/blob/ab848acc7f9127e4623cd7ce395314d160e2fb28/src/UserInterface/ColorMapPresetNames.js)
* Put the code that @PaulHax mentioned within a `window.onload` function (or `$(document).ready`).

In the end, this is how the code looks for me:

```
<div id="3drender" class="itk-vtk-viewer" data-viewport="1200x768"></div>
<script>
    window.onload = function() {
      itkVtkViewer.createViewer(document.getElementById("3drender"), {
        image: new URL('https://data.kitware.com/api/v1/file/625d10dc4acac99f426404e0/download/chameleon.nrrd'),
        rotate: false,
      }).then((viewer) => {
        viewer.setBackgroundColor([1, 1, 1])
        setTimeout(() => viewer.setImageColorMap('Viridis (matplotlib)', 0), 0)
      })
    }
</script>
```
