### ISSUE TITLE
Inline example no longer works

### ISSUE THREAD

**Issue by DrKenHo-crick** [Kitware/itk-vtk-viewer#492]
The example link below no longer works.
https://kitware.github.io/itk-vtk-viewer/docs/viewer.html

https://kitware.github.io/itk-vtk-viewer/app/?fileToLoad=https://data.kitware.com/api/v1/file/564a65d58d777f7522dbfb61/download/data.nrrd

**Comment by PaulHax** [comment]
You right!  Thank you for the issue.
