### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by PaulHax** [Kitware/itk-vtk-viewer#514]
We can't load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/itk-vtk-viewer) because the package is over 100 MB.  

@thewtex Remove files or increase the limit?

**Comment by thewtex** [comment]
> itk-vtk-viewer had 61 806 CDN hits in the last month

Not to shabby :1234: :dog: 

Yes, we need to get under 100 MB. Addressed in #515
