### ISSUE TITLE
ConnectionLess use of viewer

### ISSUE THREAD

**Issue by idoRosen25** [Kitware/itk-vtk-viewer#556]
i wish to be able to use the viewer in my app, which does not have internet connection (installed on a machine with no access to the internet). it is possible? is there a way to install all required packages locally?

**Comment by PaulHax** [comment]
Is possible.  Just need the itkVtkViewer.js file.  It bundles all needed packages.

**Comment by idoRosen25** [comment]
i tried to copy the file from the CDN but it still shows errors related to jsdelivr. can you be more specific on which file i need?

**Comment by idoRosen25** [comment]
And then I can copy the dust into my project and it will work? I still don't fully understand how to integrate it for offline usage

**Comment by PaulHax** [comment]
Both ways could work.  There are some .HTML files in the dist directory that show how to use.

**Comment by idoRosen25** [comment]
will updated to the repo have any impact on my use in the future?

**Comment by PaulHax** [comment]
Should not.  After your integration, check your network traffic?

**Comment by idoRosen25** [comment]
Great! this is working as it should! great help!!!
