### ISSUE TITLE
createViewer silently failing

### ISSUE THREAD

**Issue by bnmajor** [Kitware/itk-vtk-viewer#566]
It looks like after [991b2a1](https://github.com/Kitware/itk-vtk-viewer/commit/991b2a12b7397bffadf2614880d2a8503fa8c47b) calling `createViewer` silently fails somewhere along the line. With `itkwidgets` the viewer is created but it seems the data is not assigned and we just get an empty viewer.

Reverting back to [3f3bf98](https://github.com/Kitware/itk-vtk-viewer/commit/3f3bf98138d270d4aa7f8a3d079bbbff73a64403) works as expected.

@PaulHax I'm taking a look now but if you have any thoughts on this I'd appreciate it!

**Comment by PaulHax** [comment]
That commit broke the GUI's, but cuz I'm a dum dum and used refactor(), semantic versioning did not trigger a release so was holding off on merging: https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/pull/103

Would be good to pin viewer and viewerUI versions that itkwidgets is using.

**Comment by PaulHax** [comment]
@bnmajor Also need to merge this one down now that we have a release going for itk-vtk-viewer: https://github.com/InsightSoftwareConsortium/itk-viewer-material-ui/pull/33
