### ISSUE TITLE
Cinematic Volume Rendering updates

### ISSUE THREAD

**Issue by thewtex** [Kitware/itk-vtk-viewer#583]
- [ ] Remove Local Ambient Occlusion tooling
- [ ] Simplify Volumetric Scattering toggle to both add a Light and enable the feature
- [ ] Slider for the scattering blend -- default to 0.5
- [ ] Add Viewer/ ImJoy API programmatic interface
- [ ] Add to Bootstrap UI
- [ ] Add overflow/scrollbar/ prevent overlap with the plane sliders

**Comment by PaulHax** [comment]
Disable slider when more than 1 component where cinematic rendering not supported.

Start "Volumetric Scattering" slider at 0, then when slider is not 0, add directional light, remove headlight?  So no checkbox, disable Volumetric Scattering by dragging slider to 0?

**Comment by thewtex** [comment]
> Start "Volumetric Scattering" slider at 0, then when slider is not 0, add directional light, remove headlight? So no checkbox, disable Volumetric Scattering by dragging slider to 0?

:+1: for simple user experience / interface
