### ISSUE TITLE
Changing axes arrows appearance

### ISSUE THREAD

**Issue by LeviEyal** [Kitware/itk-vtk-viewer#662]
Hey there!
I was wondering if there a way to change the appearance of the axes arrows:
![image](https://user-images.githubusercontent.com/48846533/226183980-fb8f738a-d151-4616-bfee-aef81b409967.png)

I need to change the colors and length of each arrow. Is it possible?
Thanks a lot!

**Comment by PaulHax** [comment]
Hello!

We'll need to modify `itkVtkViewProxy`, which owns the `orientationWidget`.
https://github.com/Kitware/itk-vtk-viewer/blob/master/src/Rendering/VTKJS/vtk/ItkVtkViewProxy.js#L523

`itkVtkViewProxy`'s superclass, `vtkViewProxy`, creates the `orientationWidget`.

Is that enough to get started?

**Comment by LeviEyal** [comment]
Yes thank you!
