### ISSUE TITLE
Set colour for  different layer in conglomerate image.

### ISSUE THREAD

**Issue by jonSeetrue** [Kitware/itk-vtk-viewer#663]
@thewtex  Hi is there a limit for the layer numbers with a conglomerate image?
 I would like to load many different Nrrd files into a conglomerate image and have the option of setting the color for each layer differently.

**Comment by PaulHax** [comment]
There is no limit to number of components in a conglomerate image.  However, only 4 can be viewed at once.

**Comment by jonSeetrue** [comment]
is there a workaround for viewing more than 4 components? 
does this require a change in the code?
