### ISSUE TITLE
Embedding the ITK-VTK-Viewer doesn't work

### ISSUE THREAD

**Issue by EricMoerthVis** [Kitware/itk-vtk-viewer#686]

**Comment by PaulHax** [comment]
@EricMoerthVis PR #679 fix the viewer for your case?

**Comment by EricMoerthVis** [comment]
I was waiting for the pull request to be merged. I can try it out before this happens as well

**Comment by EricMoerthVis** [comment]
Unfortunatelly I still get the error:
XHRGET
http://localhost:3000/src/itk/web-workers/min-bundles/pipeline.worker.js
[HTTP/1.1 404 Not Found 4084ms]

**Comment by EricMoerthVis** [comment]
Just tried, I unfortunately still get the same error:
XHR  GET    http://localhost:3000/src/itk/web-workers/min-bundles/pipeline.worker.js   [HTTP/1.1 404 Not Found 4071ms]

**Comment by PaulHax** [comment]
There are some lazily loaded runtime assets (pipeline.worker.js, *.wasm) that need to be next to itkVtkViewer.js.  Try copying the whole `dist` folder into your public directory.

**Comment by EricMoerthVis** [comment]
I will try that and let you know if it works
